[2022-11-20T13:12:20.062+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Call_Center_ETL_DAG.insert_customer_data manual__2022-11-20T13:11:29.360405+00:00 [queued]>
[2022-11-20T13:12:20.085+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: Call_Center_ETL_DAG.insert_customer_data manual__2022-11-20T13:11:29.360405+00:00 [queued]>
[2022-11-20T13:12:20.086+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-20T13:12:20.087+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2022-11-20T13:12:20.088+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-20T13:12:20.134+0000] {taskinstance.py:1383} INFO - Executing <Task(MySqlOperator): insert_customer_data> on 2022-11-20 13:11:29.360405+00:00
[2022-11-20T13:12:20.148+0000] {standard_task_runner.py:55} INFO - Started process 762 to run task
[2022-11-20T13:12:20.163+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'Call_Center_ETL_DAG', 'insert_customer_data', 'manual__2022-11-20T13:11:29.360405+00:00', '--job-id', '161', '--raw', '--subdir', 'DAGS_FOLDER/call_center_dag.py', '--cfg-path', '/tmp/tmprhwowcpz']
[2022-11-20T13:12:20.164+0000] {standard_task_runner.py:83} INFO - Job 161: Subtask insert_customer_data
[2022-11-20T13:12:20.315+0000] {task_command.py:376} INFO - Running <TaskInstance: Call_Center_ETL_DAG.insert_customer_data manual__2022-11-20T13:11:29.360405+00:00 [running]> on host 9eba6bc17a61
[2022-11-20T13:12:20.933+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Abdelrhman Yassein
AIRFLOW_CTX_DAG_ID=Call_Center_ETL_DAG
AIRFLOW_CTX_TASK_ID=insert_customer_data
AIRFLOW_CTX_EXECUTION_DATE=2022-11-20T13:11:29.360405+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-20T13:11:29.360405+00:00
[2022-11-20T13:12:20.944+0000] {mysql.py:84} INFO - Executing: 
        INSERT INTO customers(customer_name,city,state, sentiment)
        SELECT 
            customer_name,
            city,
            state,
            sentiment
        FROM
            staging_call
        WHERE
            id IS NOT NULL;
        
[2022-11-20T13:12:21.082+0000] {base.py:71} INFO - Using connection ID 'mysql_conn_id' for task execution.
[2022-11-20T13:12:21.470+0000] {sql.py:315} INFO - Running statement: 
        INSERT INTO customers(customer_name,city,state, sentiment)
        SELECT 
            customer_name,
            city,
            state,
            sentiment
        FROM
            staging_call
        WHERE
            id IS NOT NULL;
        , parameters: None
[2022-11-20T13:12:24.031+0000] {sql.py:324} INFO - Rows affected: 32941
[2022-11-20T13:12:24.251+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=Call_Center_ETL_DAG, task_id=insert_customer_data, execution_date=20221120T131129, start_date=20221120T131220, end_date=20221120T131224
[2022-11-20T13:12:24.364+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-11-20T13:12:24.444+0000] {taskinstance.py:2623} INFO - 3 downstream tasks scheduled from follow-on schedule check
